per_page: 5
words_list_column: 4
take_num_lesson: 10
default_size_word_answers: 4
action_type:
  follow: 1
  unfollow: 2
  followed: 3
  unfollowed: 4
  create_lesson: 5
  login: 6
  create_category: 7
  destroy_category: 8
  create_word: 9
  destroy_word: 10
  finish_lesson: 11
activity_time_format: "%H:%M:%S %d/%m/%Y"
max_num_word_answer: 6
min_num_word_answer: 4
default_num_answer: 0
check_finish: "Finish"
profile_title:
  user_all: "All User"
  follower: "Follower"
  following: "Following"
  history: "History"
categories_num_homepage: 17
lesson_home: 6
